In [157]:
import pandas as pd
import numpy as np
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import KFold 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.model_selection import RepeatedStratifiedKFold
import csv
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler

In [158]:
train_data=pd.read_csv('data/train.csv')
test_data=pd.read_csv('data/test.csv')

In [159]:
train_data[train_data['outcome_group']==0.0]

,age,sex,country,latitude,longitude,chronic_disease_binary,Confirmed,Deaths,Recovered,Active,Incident_Rate,Case_Fatality_Ratio,outcome_group
6,65,0.0,21.0,19.420820,76.050130,0.0,2812980,54649,2400727,357604,2284.297169,1.942744,0.0
40,73,1.0,27.0,14.584244,121.176289,0.0,747288,13297,603746,130245,681.949809,1.779368,0.0
47,25,0.0,27.0,14.470810,121.427050,0.0,747288,13297,603746,130245,681.949809,1.779368,0.0
63,34,0.0,27.0,14.595800,120.977200,0.0,747288,13297,603746,130245,681.949809,1.779368,0.0
90,62,1.0,21.0,13.083620,80.282520,0.0,886673,12719,858075,15879,1139.078325,1.434463,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17107,74,0.0,27.0,14.380000,121.050000,0.0,747288,13297,603746,130245,681.949809,1.779368,0.0
17116,33,1.0,27.0,10.333330,123.750000,0.0,747288,13297,603746,130245,681.949809,1.779368,0.0
17130,62,0.0,27.0,14.595800,120.977200,0.0,747288,13297,603746,130245,681.949809,1.779368,0.0
17143,43,1.0,21.0,13.083620,80.282520,0.0,886673,12719,858075,15879,1139.078325,1.434463,0.0
17211,28,1.0,27.0,14.580000,121.030000,0.0,747288,13297,603746,130245,681.949809,1.779368,0.0

In [160]:
train_data[train_data['outcome_group']==1.0]

,age,sex,country,latitude,longitude,chronic_disease_binary,Confirmed,Deaths,Recovered,Active,Incident_Rate,Case_Fatality_Ratio,outcome_group
0,18,0.0,21.0,25.49096,85.93903,0.0,265527,1576,262371,1580,212.762145,0.593537,1.0
2,46,1.0,21.0,13.08362,80.28252,0.0,886673,12719,858075,15879,1139.078325,1.434463,1.0
3,21,0.0,21.0,13.08362,80.28252,0.0,886673,12719,858075,15879,1139.078325,1.434463,1.0
4,27,1.0,21.0,26.28361,87.20347,0.0,265527,1576,262371,1580,212.762145,0.593537,1.0
5,24,1.0,21.0,24.45712,85.13749,0.0,265527,1576,262371,1580,212.762145,0.593537,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17204,55,0.0,21.0,12.30906,76.65303,0.0,997004,12567,956170,28267,1475.672533,1.260476,1.0
17205,53,0.0,21.0,28.36145,77.50704,0.0,617194,8811,598535,9848,259.453056,1.427590,1.0
17207,29,0.0,21.0,13.08362,80.28252,0.0,886673,12719,858075,15879,1139.078325,1.434463,1.0
17209,30,1.0,21.0,24.94452,86.26404,0.0,265527,1576,262371,1580,212.762145,0.593537,1.0
17210,59,1.0,21.0,12.68224,79.98008,0.0,886673,12719,858075,15879,1139.078325,1.434463,1.0

In [161]:
train_data[train_data['outcome_group']==2.0]

,age,sex,country,latitude,longitude,chronic_disease_binary,Confirmed,Deaths,Recovered,Active,Incident_Rate,Case_Fatality_Ratio,outcome_group
1,27,0.0,27.0,7.070000,125.600000,0.0,747288,13297,603746,130245,681.949809,1.779368,2.0
12,38,0.0,27.0,14.630000,121.030000,0.0,747288,13297,603746,130245,681.949809,1.779368,2.0
19,53,0.0,27.0,13.790060,121.013160,0.0,747288,13297,603746,130245,681.949809,1.779368,2.0
24,59,1.0,27.0,14.595800,120.977200,0.0,747288,13297,603746,130245,681.949809,1.779368,2.0
27,25,1.0,27.0,14.630000,121.030000,0.0,747288,13297,603746,130245,681.949809,1.779368,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17190,67,1.0,27.0,14.580000,121.030000,0.0,747288,13297,603746,130245,681.949809,1.779368,2.0
17198,29,1.0,27.0,15.975780,120.567090,0.0,747288,13297,603746,130245,681.949809,1.779368,2.0
17202,35,1.0,27.0,10.333330,123.750000,0.0,747288,13297,603746,130245,681.949809,1.779368,2.0
17206,53,1.0,27.0,10.287693,123.976852,0.0,747288,13297,603746,130245,681.949809,1.779368,2.0
17208,47,0.0,27.0,16.688140,121.549920,0.0,747288,13297,603746,130245,681.949809,1.779368,2.0

In [162]:
under_sampler=RandomUnderSampler(random_state=42,sampling_strategy='auto')
X=train_data.iloc[:,:-1]#train_data[['age','sex','country','latitude', 'longitude','Confirmed','Deaths', 'Recovered', 'Active', 'Incident_Rate', 'Case_Fatality_Ratio']]
y=train_data.iloc[:,-1]#train_data['outcome_group']

In [229]:
X_resampled,y_resampled=under_sampler.fit_resample(X,y)

X_resampled_train, X_resampled_validation, y_resampled_train, y_resampled_validation = train_test_split(X_resampled, y_resampled,test_size=0.2, shuffle=True)


# Tuning n_neighbours

#### code skeleton to view individual fold score adapted from https://www.askpython.com/python/examples/k-fold-cross-validation

knn=KNeighborsClassifier(n_neighbors=6,weights='uniform',p=2)
kf = KFold(n_splits=5)
kf_splits=kf.split(X_resampled_train)
trans = MinMaxScaler()
pipeline = Pipeline(steps=[('t', trans), ('m', knn)])
model=pipeline
f1_scores = []
f1_scores_deceased=[]
f1_scores_hospitalised=[]
f1_scores_nonhospitalised=[]
accuracy=[]
for train_index , test_index in kf_splits:
    X_train_fold = X_resampled_train.iloc[train_index,:]
    X_validation_fold = X_resampled_train.iloc[test_index,:]
    y_train_fold = y_resampled_train.iloc[train_index]
    y_validation_fold = y_resampled_train.iloc[test_index]
     
    model.fit(X_train_fold,y_train_fold)
    pred_values = model.predict(X_validation_fold)
     
    f1 = f1_score(pred_values , y_validation_fold, average='macro')
    f1_deceased=f1_score(pred_values, y_validation_fold,average=None)[0]
    f1_hospitalised=f1_score(pred_values, y_validation_fold,average=None)[1]
    f1_nonhospitalised=f1_score(pred_values, y_validation_fold,average=None)[2]
    acc=accuracy_score(pred_values, y_validation_fold)
    f1_scores.append(f1)
    f1_scores_deceased.append(f1_deceased)
    f1_scores_hospitalised.append(f1_hospitalised)
    f1_scores_nonhospitalised.append(f1_nonhospitalised)
    accuracy.append(acc)
     
avg_f1_score = sum(f1_scores)/5
avg_f1_deceased = sum(f1_scores_deceased)/5
avg_f1_hospitalised = sum(f1_scores_hospitalised)/5
avg_f1_nonhospitalised = sum(f1_scores_nonhospitalised)/5
avg_accuracy=sum(accuracy)/5


print("Scores of folds: ", f1_scores)
print('avg_f1_macro:', avg_f1_score)
print('avg_f1_deceased', avg_f1_deceased)
print('avg_f1_hospitalised', avg_f1_hospitalised)
print('avg_f1_nonhospitalised', avg_f1_nonhospitalised)
print('avg_accuracy', avg_accuracy)

Scores of folds:  [0.7776741363228051, 0.7566034998879086, 0.7473471097719949, 0.7658086603851016, 0.7619438711564831]
avg_f1_macro: 0.7618754555048587
avg_f1_deceased 0.6701758622040259
avg_f1_hospitalised 0.8728592944066207
avg_f1_nonhospitalised 0.7425912099039294
avg_accuracy 0.7600283016395734

In [230]:
model.fit(X_resampled_train, y_resampled_train)

Pipeline(steps=[('t', MinMaxScaler()),
                ('m', KNeighborsClassifier(n_neighbors=6))])

In [231]:
y_predict=model.predict(X_resampled_validation)

In [232]:
model.score(X_resampled_validation,y_resampled_validation)

0.7696160267111853

In [234]:
model.fit(X_resampled_train,y_resampled_train)
preds_final=model.predict(test_data)

def create_submission_file(y_preds, file_name): 
    with open(file_name, 'w') as csvfile:
        wr = csv.writer(csvfile, quoting=csv.QUOTE_ALL) 
        wr.writerow(["Id", "Prediction"])
        for i, pred in enumerate(y_preds):
            wr.writerow([str(i), str(pred)]) 

df=pd.DataFrame(preds_final)
df[0]=df[0].astype('int').astype('string')

create_submission_file(df[0], 'submission_KNN.csv')